Fortigate-Gui/Models/Ip4Policy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fortigate_Gui.Models
{
    public class Ip4Policy
    {
        public int Ip4PolicyID { get; set; }

        [Display(Name = "Source Address")]
        public int? SourceInterfaceID { get; set; }

        [ForeignKey("SourceInterfaceID")]
        public virtual Zone SourceInterface { get; set; }

        [Display(Name = "Destination Interface")]
        public int? DestinationInterfaceID { get; set; }


        [ForeignKey("DestinationInterfaceID")]
        public virtual Zone DestinationInterface { get; set; }
        [Display(Name = "Source Address")]
        [Required(ErrorMessage = "Source Address is required.")]
        public string SourceAddress { get; set; }

        [Display(Name = "Destination Address")]
        [Required(ErrorMessage = "Destination Address is required.")]
        public string DestinationAddress { get; set; }
        public List<Ip4PolicyService> Ip4PolicyServices { get; set; }

        [Display(Name = "Action")]
        public virtual int? ActionID { get; set; }
        public Action Action { get; set; }

        [Display(Name = "NAT")]
        public virtual int? NatID { get; set; }
        public Nat Nat { get; set; }

        public List<ZoneInterface> ZoneInterfaces { get; set; }
        public bool DnsFilter { get; set; }
        public bool AvFilter { get; set; }
        public bool AppFilter { get; set; }
        public bool SslFilter { get; set; }
        public bool WebFilter { get; set; }
        public bool IpsFilter { get; set; }

        public bool ProxyFilter { get; set; }
    }
}

Fortigate-Gui/Controllers/Ip4PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fortigate_Gui.Data;
using Fortigate_Gui.Models;
using Fortigate_Gui.ViewModels;
using Fortigate_Gui.Helper;
using Fortigate_Gui.ValidationAttributes;

namespace Fortigate_Gui.Controllers
{
    public class Ip4PolicyController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Ip4PolicyController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ip4Policy
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ip4Policies.ToListAsync());
        }

        // GET: Ip4Policy/Create
        [HttpGet]
        //Returning JSON Object to SelectList
        public async Task<JsonResult> FetchSourceAddress(int ID)
        {
            Zone zone = await _context.Zones.SingleOrDefaultAsync(x => x.ZoneID == ID);
            var data = _context.FirewallAddresses
                .Where(fw => fw.AssociatedZone == zone.Name)
                .Select(l => new { Value = l.Name, Text = l.Name });
            return Json(data, new Newtonsoft.Json.JsonSerializerSettings());
        }

        [HttpGet]
        //Returning JSON Object to SelectList
        public async Task<JsonResult> FetchDestinationAddress(int ID)
        {
            Zone zone = await _context.Zones.SingleOrDefaultAsync(x => x.ZoneID == ID);
            var data = _context.FirewallAddresses
                .Where(fw => fw.AssociatedZone == zone.Name)
                .Select(l => new { Value = l.Name, Text = l.Name });
            return Json(data, new Newtonsoft.Json.JsonSerializerSettings());
        }

        [NoDirectAccessAttribute]
        public async Task<IActionResult> Create()
        {
            //Searching Zones to Fill Up selectlist
            Zone zone = await _context.Zones.FirstOrDefaultAsync();
            List<FirewallAddress> firewallAddresses = await _context.FirewallAddresses
                .Where(fw => fw.AssociatedZone == zone.Name).ToListAsync();


            CreateIp4PolicyViewModel viewModel = new CreateIp4PolicyViewModel
            {
                //Fill Up View
                ip4Policy = new Ip4Policy(),
                SourceInterface = new SelectList(await _context.Zones.ToListAsync(), "ZoneID", "Name"),
                DestinationInterface = new SelectList(await _context.Zones.ToListAsync(), "ZoneID", "Name"),
                SourceAddress = new SelectList(firewallAddresses, "Name", "Name"),
                DestinationAddress = new SelectList(firewallAddresses, "Name", "Name"),
                Actions = new SelectList(await _context.Actions.ToListAsync(), "ActionID", "Name"),
                Nat = new SelectList(await _context.Nat.ToArrayAsync(), "NatID", "Name"),
                SelectedService = new List<int>(),
                ServiceList = new SelectList(_context.Services, "ServiceID", "Name")
            };
            return View(viewModel);
        }

        // POST: Ip4Policy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateIp4PolicyViewModel viewModel)
        {
            Ip4Policy policy = viewModel.ip4Policy;
            if (ModelState.IsValid)
            {
                List<Ip4PolicyService> newLines = new List<Ip4PolicyService>();
                if (viewModel.SelectedService != null)
                {
                    //Many to Many relation add

                    foreach (int serviceID in viewModel.SelectedService)
                    {
                        Ip4PolicyService ip4PolicyService = new Ip4PolicyService();
                        ip4PolicyService.ServiceID = serviceID;
                        ip4PolicyService.Ip4PolicyID = viewModel.ip4Policy.Ip4PolicyID;

                        newLines.Add(ip4PolicyService);
                    }
                }

                //Save to DB
                _context.Add(viewModel.ip4Policy);
                await _context.SaveChangesAsync();

                //Get policy
                Ip4Policy ip4Policy = await _context.Ip4Policies
                    .Where(x => x.Ip4PolicyID == viewModel.ip4Policy.Ip4PolicyID)
                    .Include(y => y.Ip4PolicyServices)
                    .SingleOrDefaultAsync();
                foreach (Ip4PolicyService ip4PolicyService1 in newLines)
                {
                    //Many to Many Add
                    ip4Policy.Ip4PolicyServices.Add(ip4PolicyService1);
                }

                await _context.SaveChangesAsync();
                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", await _context.Ip4Policies.ToListAsync()) });
            }
            //fill up view when modelstate is invalid
            viewModel.SourceInterface = new SelectList(await _context.Zones.ToListAsync(), "ZoneID", "Name");
            viewModel.DestinationInterface = new SelectList(await _context.Zones.ToListAsync(), "ZoneID", "Name");
            viewModel.Nat = new SelectList(await _context.Nat.ToArrayAsync(), "NatID", "Name");
            viewModel.Actions = new SelectList(await _context.Actions.ToListAsync(), "ActionID", "Name");
            viewModel.SelectedService = new List<int>();
            viewModel.ServiceList = new SelectList(_context.Services, "ServiceID", "Name");
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Create", viewModel) }); 
        }

        // GET: Ip4Policy/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //check if id is null
            if (id == null)
            {
                return NotFound();
            }
            //Get ipv4policy from id
            Ip4Policy ip4Policy = await _context.Ip4Policies
                .Include(x => x.Ip4PolicyServices)
                .Include(x => x.SourceInterface)
                .Include(x => x.DestinationInterface)
                .SingleOrDefaultAsync(y => y.Ip4PolicyID == id);
            //Getting Source and DestinationInterface to Fill Up SelectList FirewallAddresses
            Zone zone1 = ip4Policy.SourceInterface;
            Zone zone2 = ip4Policy.DestinationInterface;

            List<FirewallAddress> SourceAddresses = await _context.FirewallAddresses
              .Where(fw => fw.AssociatedZone == zone1.Name).ToListAsync();
            List<FirewallAddress> DestinationAddresses = await _context.FirewallAddresses
               .Where(fw => fw.AssociatedZone == zone2.Name).ToListAsync();
            

            EditIp4PolicyViewModel viewModel = new EditIp4PolicyViewModel
            {
                //fill view with selectlist
                ip4Policy = ip4Policy,
                SourceInterface = new SelectList(await _context.Zones.ToListAsync(), "ZoneID", "Name", ip4Policy.SourceInterfaceID),
                DestinationInterface = new SelectList(await _context.Zones.ToListAsync(), "ZoneID", "Name", ip4Policy.DestinationInterfaceID),
                Actions = new SelectList(await _context.Actions.ToListAsync(), "ActionID", "Name", ip4Policy.ActionID),
                Nat = new SelectList(await _context.Nat.ToArrayAsync(), "NatID", "Name", ip4Policy.NatID),
                SourceAddress = new SelectList(SourceAddresses, "Name", "Name", ip4Policy.SourceAddress),
                DestinationAddress = new SelectList(DestinationAddresses, "Name", "Name", ip4Policy.DestinationAddress),
                //Many to Many relationship
                ServiceList = new SelectList(_context.Services, "ServiceID", "Name"),
                SelectedService = ip4Policy.Ip4PolicyServices.Select(x => x.ServiceID)
            };

            if (ip4Policy == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: Ip4Policy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditIp4PolicyViewModel viewModel)
        {
            Ip4Policy ip4Policy = await _context.Ip4Policies
                .Include(i => i.Ip4PolicyServices)
                .SingleOrDefaultAsync(x => x.Ip4PolicyID == id);
            if (id != viewModel.ip4Policy.Ip4PolicyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //viewModel to ip4policy
                ip4Policy.NatID = viewModel.ip4Policy.NatID;
                ip4Policy.SourceInterfaceID = viewModel.ip4Policy.SourceInterfaceID;
                ip4Policy.DestinationInterfaceID = viewModel.ip4Policy.DestinationInterfaceID;
                ip4Policy.SourceAddress = viewModel.ip4Policy.SourceAddress;
                ip4Policy.DestinationAddress = viewModel.ip4Policy.DestinationAddress;
                ip4Policy.ActionID = viewModel.ip4Policy.ActionID;
                ip4Policy.NatID = viewModel.ip4Policy.NatID;
                ip4Policy.DnsFilter = viewModel.ip4Policy.DnsFilter;
                ip4Policy.AppFilter = viewModel.ip4Policy.AppFilter;
                ip4Policy.AvFilter = viewModel.ip4Policy.AvFilter;
                ip4Policy.IpsFilter = viewModel.ip4Policy.IpsFilter;
                ip4Policy.ProxyFilter = viewModel.ip4Policy.ProxyFilter;
                ip4Policy.SslFilter = viewModel.ip4Policy.SslFilter;

Fortigate-Gui/Views/Ip4Policy/Create.cshtml
@model Fortigate_Gui.ViewModels.CreateIp4PolicyViewModel

@{
    ViewData["Title"] = "Create - Ip4Policy";
    Layout = null;
}

<form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="ip4Policy.SourceInterfaceID" class="control-label"></label>
        <select asp-for="ip4Policy.SourceInterfaceID" id="SelectedSrcInterface" asp-items="Model.SourceInterface" class="form-control"></select>
        <span asp-validation-for="ip4Policy.SourceInterfaceID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.DestinationInterfaceID" class="control-label"></label>
        <select asp-for="ip4Policy.DestinationInterfaceID" id="SelectedDstInterface" asp-items="Model.DestinationInterface" class="form-control"></select>
        <span asp-validation-for="ip4Policy.DestinationInterfaceID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.SourceAddress" class="control-label"></label>
        <select asp-for="ip4Policy.SourceAddress" id="SelectedSrcAddress" class="form-control" asp-items="Model.SourceAddress"><option value="all" >all</option></select>
        <span asp-validation-for="ip4Policy.SourceAddress" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="form-group">
            <label asp-for="ip4Policy.DestinationAddress" class="control-label"></label>
            <select asp-for="ip4Policy.DestinationAddress" id="SelectedDstAddress" asp-items="Model.DestinationAddress" class="form-control"><option value="all">all</option></select>
            <span asp-validation-for="ip4Policy.DestinationAddress" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.ActionID" class="control-label"></label>
        <select asp-for="ip4Policy.ActionID" asp-items="Model.Actions" id="type" class="form-control"></select>
        <span asp-validation-for="ip4Policy.ActionID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.NatID" class="control-label"></label>
        <select asp-for="ip4Policy.NatID" asp-items="Model.Nat" id="type" class="form-control"></select>
        <span asp-validation-for="ip4Policy.NatID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SelectedService" class="control-label"></label>
        <select class="custom-select" multiple asp-for="SelectedService" asp-items="Model.ServiceList"></select>
    </div>

    <div id="div_hide">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.DnsFilter">
            <label class="form-check-label" asp-for="ip4Policy.DnsFilter">
                DNS_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.AppFilter">
            <label class="form-check-label" asp-for="ip4Policy.AppFilter">
                APP_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.AvFilter">
            <label class="form-check-label" asp-for="ip4Policy.AvFilter">
                AV_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.IpsFilter">
            <label class="form-check-label" asp-for="ip4Policy.IpsFilter">
                IPS_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.ProxyFilter">
            <label class="form-check-label" asp-for="ip4Policy.ProxyFilter">
                PROXY_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.SslFilter">
            <label class="form-check-label" asp-for="ip4Policy.SslFilter">
                SSL_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.WebFilter">
            <label class="form-check-label" asp-for="ip4Policy.WebFilter">
                WEB_FILTER
            </label>
        </div>
    </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary col col-12" />
        </div>
   
</form>

<script>
    var DestinationUrl = '@Url.Action("FetchDestinationAddress")';
    var Destinations = $('#SelectedDstAddress');
    
            $('#SelectedDstInterface').change(function() {
                Destinations.empty();
                $.getJSON(DestinationUrl, { ID: $(this).val() },function(data) {
					if (!data) {
						return;
					}
                    Destinations.append($('<option></option>').val('').text('Please select'));
                    Destinations.append($('<option></option>').val('all').text('all'));
					$.each(data, function(index, item) {
                        Destinations.append($('<option></option>').val(item.Value).text(item.Text));
					});
				});

            })
    var localityUrl = '@Url.Action("FetchSourceAddress")';
			var localities = $('#SelectedSrcAddress');
            $('#SelectedSrcInterface').change(function() {
				localities.empty();

				$.getJSON(localityUrl, { ID: $(this).val() },function(data) {
					if (!data) {
						return;
					}
                    localities.append($('<option></option>').val('').text('Please select'));
                    localities.append($('<option></option>').val('all').text('all'));
					$.each(data, function(index, item) {
						localities.append($('<option></option>').val(item.Value).text(item.Text));
					});
				});

			})

    $(function () {
        $('#div_hide').show()
        $('#type').change(function () {
            if ($('#type').val() == 2) {
                $('#div_hide').hide();
            } else {
                $('#div_hide').show();
            }
        });
    });
</script>

Fortigate-Gui/Views/Ip4Policy/Edit.cshtml
@model Fortigate_Gui.ViewModels.EditIp4PolicyViewModel

@{
    Layout = null;
    ViewData["Title"] = "Edit";
}

<form asp-action="Edit" asp-route-id="@Model.ip4Policy.Ip4PolicyID" onsubmit="return jQueryAjaxPost(this);">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ip4Policy.Ip4PolicyID" />
    <div class="form-group">
        <label asp-for="ip4Policy.SourceInterfaceID" class="control-label"></label>
        <select asp-for="ip4Policy.SourceInterfaceID" id="SelectedSrcInterface" asp-items="Model.SourceInterface" class="form-control"></select>
        <span asp-validation-for="ip4Policy.SourceInterfaceID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.DestinationInterfaceID" class="control-label"></label>
        <select asp-for="ip4Policy.DestinationInterfaceID" id="SelectedDstInterface" asp-items="Model.DestinationInterface" class="form-control"></select>
        <span asp-validation-for="ip4Policy.DestinationInterfaceID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.SourceAddress" class="control-label"></label>
        <select asp-for="ip4Policy.SourceAddress" id="SelectedSrcAddress" class="form-control" asp-items="Model.SourceAddress"><option value="all">all</option></select>
        <span asp-validation-for="ip4Policy.SourceAddress" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="form-group">
            <label asp-for="ip4Policy.DestinationAddress" class="control-label"></label>
            <select asp-for="ip4Policy.DestinationAddress" id="SelectedDstAddress" asp-items="Model.DestinationAddress" class="form-control"><option value="all">all</option></select>
            <span asp-validation-for="ip4Policy.DestinationAddress" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.ActionID" class="control-label"></label>
        <select asp-for="ip4Policy.ActionID" asp-items="Model.Actions" id="type" class="form-control"></select>
        <span asp-validation-for="ip4Policy.ActionID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ip4Policy.NatID" class="control-label"></label>
        <select asp-for="ip4Policy.NatID" asp-items="Model.Nat" id="type" class="form-control"></select>
        <span asp-validation-for="ip4Policy.NatID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SelectedService" class="control-label"></label>
        <select class="custom-select" multiple asp-for="SelectedService" asp-items="Model.ServiceList"></select>
    </div>

    <div id="div_hide">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.DnsFilter">
            <label class="form-check-label" asp-for="ip4Policy.DnsFilter">
                DNS_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.AppFilter">
            <label class="form-check-label" asp-for="ip4Policy.AppFilter">
                APP_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.AvFilter">
            <label class="form-check-label" asp-for="ip4Policy.AvFilter">
                AV_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.IpsFilter">
            <label class="form-check-label" asp-for="ip4Policy.IpsFilter">
                IPS_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.ProxyFilter">
            <label class="form-check-label" asp-for="ip4Policy.ProxyFilter">
                PROXY_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.SslFilter">
            <label class="form-check-label" asp-for="ip4Policy.SslFilter">
                SSL_FILTER
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="ip4Policy.WebFilter">
            <label class="form-check-label" asp-for="ip4Policy.WebFilter">
                WEB_FILTER
            </label>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary col col-12" />
    </div>

</form>

<script>
    var DestinationUrl = '@Url.Action("FetchDestinationAddress")';
    var Destinations = $('#SelectedDstAddress');

            $('#SelectedDstInterface').change(function() {
                Destinations.empty();
                $.getJSON(DestinationUrl, { ID: $(this).val() },function(data) {
					if (!data) {
						return;
					}
                    Destinations.append($('<option></option>').val('').text('Please select'));
                    Destinations.append($('<option></option>').val('all').text('all'));
					$.each(data, function(index, item) {
                        Destinations.append($('<option></option>').val(item.Value).text(item.Text));
					});
				});

            })
    var localityUrl = '@Url.Action("FetchSourceAddress")';
			var localities = $('#SelectedSrcAddress');
            $('#SelectedSrcInterface').change(function() {
				localities.empty();

				$.getJSON(localityUrl, { ID: $(this).val() },function(data) {
					if (!data) {
						return;
					}
                    localities.append($('<option></option>').val('').text('Please select'));
                    localities.append($('<option></option>').val('all').text('all'));
					$.each(data, function(index, item) {
						localities.append($('<option></option>').val(item.Value).text(item.Text));
					});
				});

			})

    $(function () {
        $('#div_hide').show()
        $('#type').change(function () {
            if ($('#type').val() == 2) {
                $('#div_hide').hide();
            } else {
                $('#div_hide').show();
            }
        });
    });
</script>

Fortigate-Gui/Views/Ip4Policy/Index.cshtml
@model IEnumerable<Fortigate_Gui.Models.Ip4Policy>

@{
    ViewData["Title"] = "IPv4 Policy";
}

<div class="row">
    <div class="col-4">
        <p>
            <a onclick="showInPopup('@Url.Action("Create","Ip4Policy",null,Context.Request.Scheme)','Add Ip4Policy')" class="btn btn-outline-danger">New Ip4Policy</a>
        </p>
    </div>
    <div class="col-8">
        <h1><i class="fas fa-code"></i> Ip4Policy</h1>
    </div>
</div>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

Fortigate-Gui/Views/Ip4Policy/_ViewAll.cshtml
@model IEnumerable<Fortigate_Gui.Models.Ip4Policy>
<script>
    $(document).ready(function () {
        $("#datatable").DataTable();
    });
</script>

<table class="table" id="datatable">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.SourceAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DestinationAddress)
            </th>

            <th class="text-right">Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
<tbody>
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.SourceAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationAddress)
        </td>

        <td class="text-right">
            <a onclick="showInPopup('@Url.Action("Edit","Ip4Policy",new { id = item.Ip4PolicyID },Context.Request.Scheme)','Edit Ip4Policy')" class="btn btn-outline-danger"><i class="btn-outline-danger far fa-edit"></i></a>
            <form asp-action="Delete" asp-route-id="@item.Ip4PolicyID" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                <button type="submit" class="btn btn-outline-danger"><i class="far fa-trash-alt" aria-hidden="true"></i></button>
            </form>
            <a asp-controller="Home" asp-action="AddIp4Policy" class="btn btn-outline-danger" asp-route-id="@item.Ip4PolicyID"><i class="far fa-plus-square"></i></a>
        </td>
    </tr>
</tbody>
    }
</table>