Fortigate-Gui/Models/EnumAcces.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fortigate_Gui.Models
{
    public class EnumAcces
    {
        public int EnumAccesID { get; set; }
        public string Name { get; set; }
    }
}

Fortigate-Gui/Controllers/EnumAccesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fortigate_Gui.Data;
using Fortigate_Gui.Models;
using Fortigate_Gui.Helper;
using Microsoft.AspNetCore.Authorization;

namespace Fortigate_Gui.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EnumAccesController : Controller
    {
        //Default generated Controller with entity frameworkcore for Admin adjustments
        private readonly ApplicationDbContext _context;
        
        public EnumAccesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EnumAcces
        public async Task<IActionResult> Index()
        {
            return View(await _context.EnumAcces.ToListAsync());
        }

        // GET: EnumAcces/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EnumAcces/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnumAccesID,Name")] EnumAcces enumAcces)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enumAcces);
                await _context.SaveChangesAsync();
                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", await _context.EnumAcces.ToListAsync()) });
            }
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Create", enumAcces) });
        }

        // GET: EnumAcces/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enumAcces = await _context.EnumAcces.FindAsync(id);
            if (enumAcces == null)
            {
                return NotFound();
            }
            return View(enumAcces);
        }

        // POST: EnumAcces/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EnumAccesID,Name")] EnumAcces enumAcces)
        {
            if (id != enumAcces.EnumAccesID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(enumAcces);
                await _context.SaveChangesAsync();

                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", _context.EnumAcces.ToList()) });
            }
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Edit", enumAcces) });
        }

        // POST: EnumAcces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enumAcces = await _context.EnumAcces.FindAsync(id);
            _context.EnumAcces.Remove(enumAcces);
            await _context.SaveChangesAsync();
            return Json(new { html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", _context.EnumAcces.ToList()) });
        }

        private bool EnumAccesExists(int id)
        {
            return _context.EnumAcces.Any(e => e.EnumAccesID == id);
        }
    }
}

Fortigate-Gui/Views/EnumAcces/Create.cshtml
@model Fortigate_Gui.Models.EnumAcces

@{
    ViewData["Title"] = "Create";
    Layout = null;
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-outline-danger" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fortigate-Gui/Views/EnumAcces/Delete.cshtml
@model Fortigate_Gui.Models.EnumAcces

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EnumAcces</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EnumAccesID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Fortigate-Gui/Views/EnumAcces/Details.cshtml
@model Fortigate_Gui.Models.EnumAcces

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EnumAcces</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EnumAccesID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Fortigate-Gui/Views/EnumAcces/Edit.cshtml
@model Fortigate_Gui.Models.EnumAcces

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EnumAcces</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EnumAccesID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fortigate-Gui/Views/EnumAcces/Index.cshtml
@model IEnumerable<Fortigate_Gui.Models.EnumAcces>

@{
    ViewData["Title"] = "Acces";
}

<div class="row">
    <div class="col-4">
        <p>
            <a onclick="showInPopup('@Url.Action("Create","EnumAcces",null,Context.Request.Scheme)','Add Acces')" class="btn btn-outline-danger">New Acces</a>
        </p>
    </div>
    <div class="col-8">
        <h1><i class="fas fa-universal-access"></i> Acces</h1>
    </div>
</div>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

Fortigate-Gui/Views/EnumAcces/_ViewAll.cshtml
@model IEnumerable<Fortigate_Gui.Models.EnumAcces>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-right">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-right">
                    <a onclick="showInPopup('@Url.Action("Edit","EnumAcces",new { id = item.EnumAccesID },Context.Request.Scheme)','Edit Acces')" class="btn btn-outline-danger"><i class="btn-outline-danger far fa-edit"></i></a>
                    <form asp-action="Delete" asp-route-id="@item.EnumAccesID" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                        <button type="submit" class="btn btn-outline-danger"><i class="far fa-trash-alt" aria-hidden="true"></i></button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>