Fortigate-Gui/Controllers/EnumTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fortigate_Gui.Data;
using Fortigate_Gui.Models;
using Fortigate_Gui.Helper;
using Microsoft.AspNetCore.Authorization;

namespace Fortigate_Gui.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EnumTypeController : Controller
    {
        //Default generated Controller with entity frameworkcore for Admin adjustments
        private readonly ApplicationDbContext _context;
        public EnumTypeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EnumType
        public async Task<IActionResult> Index()
        {
            return View(await _context.EnumTypes.ToListAsync());
        }

        // GET: EnumType/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EnumType/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnumTypeID,Name")] EnumType enumType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enumType);
                await _context.SaveChangesAsync();
                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", await _context.EnumTypes.ToListAsync()) });
            }
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Create", enumType) });
        }

        // GET: EnumType/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enumType = await _context.EnumTypes.FindAsync(id);
            if (enumType == null)
            {
                return NotFound();
            }
            return View(enumType);
        }

        // POST: EnumType/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EnumTypeID,Name")] EnumType enumType)
        {
            if (id != enumType.EnumTypeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(enumType);
                await _context.SaveChangesAsync();

                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", _context.EnumTypes.ToList()) });
            }
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Edit", enumType) });
        }

        // POST: EnumType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enumType = await _context.EnumTypes.FindAsync(id);
            _context.EnumTypes.Remove(enumType);
            await _context.SaveChangesAsync();
            return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", _context.EnumTypes.ToList()) });
        }

        private bool EnumTypeExists(int id)
        {
            return _context.EnumTypes.Any(e => e.EnumTypeID == id);
        }
    }
}

Fortigate-Gui/Views/EnumType/Create.cshtml
@model Fortigate_Gui.Models.EnumType

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-outline-danger" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fortigate-Gui/Views/EnumType/Edit.cshtml
@model Fortigate_Gui.Models.EnumType

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EnumTypeID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-danger" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fortigate-Gui/Views/EnumType/Index.cshtml
@model IEnumerable<Fortigate_Gui.Models.EnumType>

@{
    ViewData["Title"] = "Type";
}

<div class="row">
    <div class="col-4">
        <p>
            <a onclick="showInPopup('@Url.Action("Create","EnumType",null,Context.Request.Scheme)','Add Type')" class="btn btn-outline-danger">New Type</a>
        </p>
    </div>
    <div class="col-8">
        <h1><i class="fab fa-typo3"></i> Type</h1>
    </div>
</div>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

Fortigate-Gui/Views/EnumType/_ViewAll.cshtml
@model IEnumerable<Fortigate_Gui.Models.EnumType>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-right">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-right">
                    <a onclick="showInPopup('@Url.Action("Edit","EnumType",new { id = item.EnumTypeID },Context.Request.Scheme)','Edit Type')" class="btn btn-outline-danger"><i class="btn-outline-danger far fa-edit"></i></a>
                    <form asp-action="Delete" asp-route-id="@item.EnumTypeID" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                        <button type="submit" class="btn btn-outline-danger"><i class="far fa-trash-alt" aria-hidden="true"></i></button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>