Fortigate-Gui/Models/EnumPhysical.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fortigate_Gui.Models
{
    public class EnumPhysical
    {
        public int EnumPhysicalID { get; set; }
        public string Name { get; set; }

    }
}

Fortigate-Gui/Controllers/EnumPhysicalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fortigate_Gui.Data;
using Fortigate_Gui.Models;
using Fortigate_Gui.Helper;
using Microsoft.AspNetCore.Authorization;

namespace Fortigate_Gui.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EnumPhysicalController : Controller
    {
        //Default generated Controller with entity frameworkcore for Admin adjustments
        private readonly ApplicationDbContext _context;

        public EnumPhysicalController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EnumPhysical
        public async Task<IActionResult> Index()
        {
            return View(await _context.EnumPhysicals.ToListAsync());
        }

        // GET: EnumPhysical/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EnumPhysical/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnumPhysicalID,Name")] EnumPhysical enumPhysical)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enumPhysical);
                await _context.SaveChangesAsync();
                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", await _context.EnumPhysicals.ToListAsync()) });
            }
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Create", enumPhysical) });
        }

        // GET: EnumPhysical/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enumPhysical = await _context.EnumPhysicals.FindAsync(id);
            if (enumPhysical == null)
            {
                return NotFound();
            }
            return View(enumPhysical);
        }

        // POST: EnumPhysical/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EnumPhysicalID,Name")] EnumPhysical enumPhysical)
        {
            if (id != enumPhysical.EnumPhysicalID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(enumPhysical);
                await _context.SaveChangesAsync();

                return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", _context.EnumPhysicals.ToList()) });
            }
            return Json(new { isValid = false, html = RenderRazorHelper.RenderRazorViewToString(this, "Edit", enumPhysical) });
        }

        // POST: EnumPhysical/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enumPhysical = await _context.EnumPhysicals.FindAsync(id);
            _context.EnumPhysicals.Remove(enumPhysical);
            await _context.SaveChangesAsync();
            return Json(new { isValid = true, html = RenderRazorHelper.RenderRazorViewToString(this, "_ViewAll", _context.EnumPhysicals.ToList()) });
        }

        private bool EnumPhysicalExists(int id)
        {
            return _context.EnumPhysicals.Any(e => e.EnumPhysicalID == id);
        }
    }
}

Fortigate-Gui/Views/EnumPhysical/Create.cshtml
@model Fortigate_Gui.Models.EnumPhysical

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-outline-danger" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fortigate-Gui/Views/EnumPhysical/Edit.cshtml
@model Fortigate_Gui.Models.EnumPhysical

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EnumPhysicalID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-outline-danger" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fortigate-Gui/Views/EnumPhysical/Index.cshtml
@model IEnumerable<Fortigate_Gui.Models.EnumPhysical>

@{
    ViewData["Title"] = "Physical";
}

<div class="row">
    <div class="col-4">
        <p>
            <a onclick="showInPopup('@Url.Action("Create","EnumPhysical",null,Context.Request.Scheme)','Add Physical')" class="btn btn-outline-danger">New Physical</a>
        </p>
    </div>
    <div class="col-8">
        <h1><i class="fas fa-dumbbell"></i> Physical</h1>
    </div>
</div>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

Fortigate-Gui/Views/EnumPhysical/_ViewAll.cshtml
@model IEnumerable<Fortigate_Gui.Models.EnumPhysical>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-right">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-right">
                    <a onclick="showInPopup('@Url.Action("Edit","EnumPhysical",new { id = item.EnumPhysicalID },Context.Request.Scheme)','Edit Physical')" class="btn btn-outline-danger"><i class="btn-outline-danger far fa-edit"></i></a>
                    <form asp-action="Delete" asp-route-id="@item.EnumPhysicalID" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                        <button type="submit" class="btn btn-outline-danger"><i class="far fa-trash-alt" aria-hidden="true"></i></button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>